baseURL = "/"
languageCode = "en-gb"
title = "AQA Computer Science Documentation"
theme = "green"
disableKinds = ["taxonomy","taxonomyTerm"]
disableHugoGeneratorInject = true

[outputs]
page = ["HTML"]
home = ["HTML", "search"]
section = ["HTML"]

[outputFormats.search]
mediaType = "application/json"
baseName = "search"
isPlainText = true

[imaging]
quality = 90